
server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://afibekirmxbzoz:4cc423cf84261108826851f0ccbc7044c7a13ce321e0878dd9357198613ef645@ec2-54-167-152-185.compute-1.amazonaws.com:5432/d8t1a3p29e08c4
    username: afibekirmxbzoz
    password: 4cc423cf84261108826851f0ccbc7044c7a13ce321e0878dd9357198613ef645
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      dll-auto: none

application:
  description: Project created for santander - DIO bootcamp dev week